name: Run Python

on:
  push:
    branches: [ main ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Python 설치
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
      - name: 실행
        run: python main.py
